### ISSUE TITLE
E/BluetoothAdapter: Bluetooth binder is null

### ISSUE THREAD

**Issue by ankurbag** [mrebollob/situm-demo#2]
I am getting this error-
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mrebollob.situmdemo, PID: 18044
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/base.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.mrebollob.situmdemo-yQ8QrDscEQnH3oGh5PAroA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libandroidPodometro.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at es.situm.sdk.v1.nat.NativePedometer.<clinit>(Unknown Source:26)
        at es.situm.sdk.v1.nat.NativePedometer.a(Unknown Source:0)
        at es.situm.sdk.v1.nat.b.<init>(Unknown Source:3)
        at es.situm.sdk.location.a.d.c.c.<init>(Unknown Source:23)
        at es.situm.sdk.location.a.d.b.b(Unknown Source:36)
        at es.situm.sdk.v1.SitumService.onStartCommand(Unknown Source:166)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Application terminated.

**Comment by ankurbag** [comment]
@mrebollob Please help
